services:

  db:
    image: postgres:16
    container_name: daily-db
    restart: "no"
    environment:
      POSTGRES_DB: daily_plan_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: java2905
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d daily_plan_project"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-app
    restart: "no"

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/daily_plan_project
      DB_USER: postgres
      DB_PASSWORD: java2905
      USER_LOGIN: kv3rk
      USER_PASSWORD: Java_2905!

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/daily/main"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata: