services:

  db:
    image: postgres:16
    container_name: daily-db
    restart: "no"
    environment:
      POSTGRES_DB: daily_plan_project
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d daily_plan_project"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daily-app
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_LOGIN: ${USER_LOGIN}
      USER_PASSWORD: ${USER_PASSWORD}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DEFAULT_GOAL_NUMBER1: ${DEFAULT_GOAL_NUMBER1}
      DEFAULT_GOAL_NUMBER2: ${DEFAULT_GOAL_NUMBER2}
      DEFAULT_GOAL_NUMBER3: ${DEFAULT_GOAL_NUMBER3}
      DEFAULT_GOAL_NUMBER4: ${DEFAULT_GOAL_NUMBER4}
      DEFAULT_GOAL_NUMBER5: ${DEFAULT_GOAL_NUMBER5}
      DEFAULT_GOAL_NUMBER6: ${DEFAULT_GOAL_NUMBER6}
      DEFAULT_GOAL_NUMBER7: ${DEFAULT_GOAL_NUMBER7}
      DEFAULT_GOAL_NUMBER8: ${DEFAULT_GOAL_NUMBER8}
      DEFAULT_GOAL_NUMBER11: ${DEFAULT_GOAL_NUMBER11}
      DEFAULT_GOAL_NUMBER12: ${DEFAULT_GOAL_NUMBER12}
      DEFAULT_GOAL_NUMBER13: ${DEFAULT_GOAL_NUMBER13}
      DEFAULT_GOAL_NUMBER14: ${DEFAULT_GOAL_NUMBER14}
      DEFAULT_GOAL_NUMBER15: ${DEFAULT_GOAL_NUMBER15}
      DEFAULT_GOAL_NUMBER16: ${DEFAULT_GOAL_NUMBER16}
      DEFAULT_GOAL_NUMBER17: ${DEFAULT_GOAL_NUMBER17}
      DEFAULT_GOAL_NUMBER20: ${DEFAULT_GOAL_NUMBER20}
      DEFAULT_GOAL_NUMBER21: ${DEFAULT_GOAL_NUMBER21}
      DEFAULT_GOAL_NUMBER22: ${DEFAULT_GOAL_NUMBER22}
      DEFAULT_GOAL_NUMBER23: ${DEFAULT_GOAL_NUMBER23}
      DEFAULT_GOAL_NUMBER24: ${DEFAULT_GOAL_NUMBER24}
      DEFAULT_GOAL_NUMBER25: ${DEFAULT_GOAL_NUMBER25}
      DEFAULT_GOAL_NUMBER26: ${DEFAULT_GOAL_NUMBER26}
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: