spring:
  application:
    name: DailyPlan
  profiles:
    active: prod
  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
default:
  goal:
    english-anki-1: ${DEFAULT_GOAL_ENGLISH_ANKI_1}
    english-anki-2: ${DEFAULT_GOAL_ENGLISH_ANKI_2}
    english-speaking: ${DEFAULT_GOAL_ENGLISH_SPEAKING}
    english-grammar: ${DEFAULT_GOAL_ENGLISH_GRAMMAR}
    english-writing: ${DEFAULT_GOAL_ENGLISH_WRITING}
    english-reading: ${DEFAULT_GOAL_ENGLISH_READING}
    english-listening: ${DEFAULT_GOAL_ENGLISH_LISTENING}
    programming-interview: ${DEFAULT_GOAL_PROGRAMMING_INTERVIEW}
    water: ${DEFAULT_GOAL_WATER}
    run: ${DEFAULT_GOAL_RUN}
    cleaning: ${DEFAULT_GOAL_CLEANING}
    toefl: ${DEFAULT_GOAL_TOEFL}
    weekly-review: ${DEFAULT_GOAL_WEEKLY_REVIEW}
    strength: ${DEFAULT_GOAL_STRENGTH}
    weekly-weigh: ${DEFAULT_GOAL_WEEKLY_WEIGH}
    job-search: ${DEFAULT_GOAL_JOB_SEARCH}
    morning-routine: ${DEFAULT_GOAL_MORNING_ROUTINE}
    evening-routine: ${DEFAULT_GOAL_EVENING_ROUTINE}
    anki-weekly-1: ${DEFAULT_GOAL_ANKI_WEEKLY_1}
    anki-weekly-2: ${DEFAULT_GOAL_ANKI_WEEKLY_2}