spring:
  application:
    name: DailyPlan
  profiles:
    active: prod
  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true
telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
    chat:
      id: ${TELEGRAM_BOT_CHAT_ID}